version: '3.8'

services:
  web:
    build: ./equipment_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./equipment_project/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
