version: '3.8'

services:
  backend:
    build: ./equipment_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./equipment_project/:/usr/src/code/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    container_name: mysql-container
    image: mysql:8.1    
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:    
      - MYSQL_ROOT_PASSWORD=masterkey
      - MYSQL_USER=user_admin
      - MYSQL_PASSWORD=masterkey
      - MYSQL_DATABASE=mysql_db
      
  frontend:
    build: ./vue-equipment
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  mysql_data:
