# Generated by Django 4.2.4 on 2023-09-01 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="equipment_type_id",
            new_name="equipment_type",
        ),
    ]
